[project]
name = "fork"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "toni.borders@informationtechconsultants.co.uk" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.4.0",
    "kagglehub[pandas-datasets]>=1.0.2",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "pycountry-convert>=0.7.2",
    "scikit-learn>=1.9.1",
]

[project.scripts]
fork = "fork:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
